### ISSUE TITLE
index.js syntax error

### ISSUE THREAD

**Issue by uberadminer** [konsumer/tplink-lightbulb#1]
/usr/local/lib/node_modules/tplink-lightbulb/index.js:62
  set (power = true, transition = 0, options = {}) {
             ^

SyntaxError: Unexpected token =

When I try to run tplight this is what the terminal spits out.

**Comment by konsumer** [comment]
What version of node are you using? I think this is related to the modern default parameters value syntax. I can rewrite it without that, though, when I get home.

**Comment by uberadminer** [comment]
node v4.2.2 npm 2.14.7

**Comment by konsumer** [comment]
Ah, yeh. If you want, just update to latest models and it should work, but I don't mind making it work for old node, too.

**Comment by konsumer** [comment]
models=nodejs (on phone)

**Comment by uberadminer** [comment]
Yea updating fixed, thanks.
