### ISSUE TITLE
[Question] Is LB130 supported?

### ISSUE THREAD

**Issue by msunjic98** [konsumer/tplink-lightbulb#11]
I saw in README that LB130 isn't tested, but at the bottom LB130 is mentioned, so I'm wondering has anyone given it a try and is it working?

**Comment by ExperimentalZeros** [comment]
Controlling the colors by HEX, and On/Off work(US version)! I cannot vauch for the acuracy as of yet. That is work in progress.

   One thing I did not get to have running is the "Timer" function. I will have to add an issue there.

   Also was wondering how to make it a "node-red" module (wrapper??), another request!

EZ

**Comment by konsumer** [comment]
It's not tested by me (I don't have the hardware) but feel free to test and report back. Others have had good luck with it.

**Comment by konsumer** [comment]
I'm going to close this issue for now, but let me know if you have any issues on LB130.

**Comment by konsumer** [comment]
I missed the node-red question. I don't use that, but feel free to make a new node-red node. I found [these instructions](https://nodered.org/docs/creating-nodes/first-node). Looks like [this](https://github.com/diegopamio/node-red-contrib-lifx) might provide some inspiration.
