### ISSUE TITLE
Seting -t parameter for a fluent color change doesn't have any effect

### ISSUE THREAD

**Issue by zubozrout** [konsumer/tplink-lightbulb#12]
Hello,
while setting transition time in raw using "transition_period" works I seem to be unable to make the light change its color fluently using this command:

> /usr/local/bin/tplight hex -t 10 10.0.0.200 "#48258b"
> Take 10 seconds to set the lightbulb to a nice shade of purple.

This one however works (as mentioned above):
`tplight raw IP '{"smartlife.iot.smartbulb.lightingservice":{"transition_light_state":{"transition_period": $DELAYINMS, "ignore_default":1, "on_off":1, "color_temp":$brightness, "hue":$hue, "saturation":$saturation}}}'`

It also looks like I may not be the only one based on this comment: https://github.com/konsumer/tplink-lightbulb/issues/11#issuecomment-319062203 but apparently @ExperimentalZeros didn't report this or I could not find it for some reason.

Could you please look into that?
Thank you very much

**Comment by zubozrout** [comment]
Oh, my mistake, sorry. I was apparently entering too much too short time in the above command as it is not a number of seconds but a number of milliseconds.

**Comment by konsumer** [comment]
Glad it worked! I added a note to `--help` to make it clearer.
