### ISSUE TITLE
Status polling for bulbs

### ISSUE THREAD

**Issue by CantonsCobb** [konsumer/tplink-lightbulb#13]
Is it possible/feasible to have a function to request the current status of a bulb? For example, I'd like to read current brightness and color.

**Comment by konsumer** [comment]
Are you using it in code or on the CLI?

**Comment by konsumer** [comment]
In code, you can use [info](https://github.com/konsumer/tplink-lightbulb#module_info) and [details](https://github.com/konsumer/tplink-lightbulb#module_details). On CLI, I just added more info to `detail`. Here is an example: `tplight details 192.168.86.149`

```json
{
  "lamp_beam_angle": 270,
  "min_voltage": 110,
  "max_voltage": 120,
  "wattage": 10,
  "incandescent_equivalent": 60,
  "max_lumens": 800,
  "color_rendering_index": 80,
  "err_code": 0,
  "sw_ver": "1.0.9 Build 160524 Rel.100333",
  "hw_ver": "1.0",
  "model": "LB120(US)",
  "description": "Smart Wi-Fi LED Bulb with Tunable White Light",
  "alias": "Godzilla",
  "mic_type": "IOT.SMARTBULB",
  "dev_state": "normal",
  "mic_mac": "50C7BF0762AA",
  "deviceId": "8012B398CEEFB2FEF8F163EDFAAC4619177E30DB",
  "oemId": "3444835A20788C514CB24B9F869A0A5E",
  "hwId": "111E35908497A05512E259BB76801E10",
  "is_factory": false,
  "disco_ver": "1.0",
  "ctrl_protocols": {
    "name": "Linkie",
    "version": "1.0"
  },
  "light_state": {
    "on_off": 1,
    "mode": "normal",
    "hue": 0,
    "saturation": 0,
    "color_temp": 3500,
    "brightness": 100
  },
  "is_dimmable": 1,
  "is_color": 0,
  "is_variable_color_temp": 1,
  "preferred_state": [
    {
      "index": 0,
      "hue": 0,
      "saturation": 0,
      "color_temp": 3500,
      "brightness": 100
    },
    {
      "index": 1,
      "hue": 0,
      "saturation": 0,
      "color_temp": 6500,
      "brightness": 50
    },
    {
      "index": 2,
      "hue": 0,
      "saturation": 0,
      "color_temp": 2700,
      "brightness": 50
    },
    {
      "index": 3,
      "hue": 0,
      "saturation": 0,
      "color_temp": 2700,
      "brightness": 1
    }
  ],
  "rssi": -51,
  "active_mode": "none",
  "heapsize": 417880
}
```

You can also get a bit less info by running any command: `tplight on 192.168.86.149`

```json
{
  "on_off": 1,
  "mode": "normal",
  "hue": 0,
  "saturation": 0,
  "color_temp": 3500,
  "brightness": 100,
  "err_code": 0
}
```

**Comment by konsumer** [comment]
As a sidenote, if you are using CLI, and you want to use the value in another script, [jq](https://github.com/stedolan/jq) is pretty handy:

```sh
LIGHT_ON=`tplight details 192.168.86.149 | jq -r .light_state.on_off`
echo $LIGHT_ON
1
```

**Comment by CantonsCobb** [comment]
I am using the command line. The details additions sounds exactly like what I am looking for, but I am unable to see those parameters. I just updated, and rain the details command. Below is the output I get. Any suggestions?

+ tplink-lightbulb@1.2.0
updated 1 package in 2.424s

C:\Users\Adam>tplight details 192.168.1.104
{
  "lamp_beam_angle": 270,
  "min_voltage": 110,
  "max_voltage": 120,
  "wattage": 10,
  "incandescent_equivalent": 60,
  "max_lumens": 800,
  "color_rendering_index": 80,
  "err_code": 0
}

**Comment by konsumer** [comment]
Hmm. Not sure. I just updated how it combines the `details` with info, and published as `1.2.1`. Try that, and see if it works any differently.

**Comment by CantonsCobb** [comment]
--version gave me 1.2.4, and the new details function works like a charm. Thanks!

**Comment by konsumer** [comment]
Sweet!
