### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by khkremer** [konsumer/tplink-lightbulb#2]
I had your software working a few weeks go (I just installed using the "npm i -g uplink-lightbulb" command). I updated today using the same command, and now I am getting this error:

MacBookPro2013:HomeAutomation khk$ tplight 
/Users/khk/npm-global/bin/tplight: line 1: use strict: command not found
/Users/khk/npm-global/bin/tplight: line 3: syntax error near unexpected token `('
/Users/khk/npm-global/bin/tplight: line 3: `var _lib = require('./lib');'
MacBookPro2013:HomeAutomation khk$ node -v
v6.9.4

As you can see, I am using node 6.9.4 (which may have gotten updated as well since I was last able to use the software. 

Any ideas about what's wrong?

**Comment by konsumer** [comment]
Hmm. I just added statics because I noticed scan, encrypt, and decrypt were unreachable without instantiating. Can you send me your code?

**Comment by konsumer** [comment]
I think I might have found it. Republished, and appreciate testing.

**Comment by khkremer** [comment]
There is no code that I added, it's just running the tplight application from the npm package. 

Thanks.

**Comment by konsumer** [comment]
Ok, try it again with the new version. Should work better. I forgot to double-check the cli wrapper.

**Comment by khkremer** [comment]
David, thanks for the quick fix. Yes, I can run the cli again, but found
another problem: When I use the "scan" parameter, I get the following
output:

tplight  scan

Press Ctrl-C to stop

undefined '-' undefined

undefined '-' undefined

undefined '-' undefined

undefined '-' undefined

undefined '-' undefined

undefined '-' undefined

undefined '-' undefined

undefined '-' undefined

^C

This also used to work. When I use the actual IP address of my bulb with
the on/off parameter, the bulb does correctly turn on or off. With the same
application the "-b" / --brightness switch does not seem to do anything.

Thanks.


Karl Heinz Kremer
PDF Acrobatics Without a Net
PDF Software Development, Training and More...

khk@khk.net
http://www.khkonsulting.com

**Comment by konsumer** [comment]
Interesting. I'm not on my home network, so I can't test, but I think I know where the issue is. I will try to fix it, tonight.

**Comment by khkremer** [comment]
Great. BTW, this is a LB110


Karl Heinz Kremer
PDF Acrobatics Without a Net
PDF Software Development, Training and More...

khk@khk.net
http://www.khkonsulting.com

**Comment by konsumer** [comment]
I think I fixed the scan issue, but I am not sure about the `brightness flag`. It works on my lightbulb, but not sure of the syntax of yours (a pcap or just the output from the wireshark when you change brightness would help.)

**Comment by khkremer** [comment]
I guess I need to setup one of my Raspberry PIs as an access point. I'll
let you know when I find some time to do that.

Thanks.


Karl Heinz Kremer
PDF Acrobatics Without a Net
PDF Software Development, Training and More...

khk@khk.net
http://www.khkonsulting.com

**Comment by konsumer** [comment]
Thanks! I'm excited to have support for more devices, but it's pretty hard to troubleshoot without having the device. The wireshark dissector in this repo makes it easy to see what it's doing, though.
