### ISSUE TITLE
Plug LEDs

### ISSUE THREAD

**Issue by konsumer** [konsumer/tplink-lightbulb#21]
The LEDs on the plug can be changed, independent from power-state. I should add support for this.

**Comment by migte** [comment]
Did this ever happen? How would I go about doing this?

**Comment by konsumer** [comment]
No. It's not something I personally need, so it's not a priority for me, but I'm happy to accept a PR. You could capture traffic from the real thing, then recreate it in the lib. Have a look at the "wireshark" section of the README. Generally it's just a matter of using `send` to send a similar message. Have a look at the rest of the lib for examples.

**Comment by migte** [comment]
Thanks! I got it working.
```javascript
/**
     * Set led-state of lightbulb
     * @module led
     * @param {Boolean} ledState On or off
     * @returns {Promise}          Resolves to output of command
     * @example
     * ```js
    // turn the LED status light on
    const light = new TPLSmartDevice('10.0.0.200')
    light.led(true)
    .then(status => {
      console.log(status)
    })
    .catch(err => console.error(err))
    ```
     */

  }, {
    key: "led",
    value: function led() {
      var _this2 = this;

      var ledState = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : true;
      return this.info().then(function (info) {
        if (typeof info.led_off !== 'undefined') {
          return _this2.send({
            system: {
              set_led_off: {
                off: ledState ? 0 : 1
              }
            }
          });
        }
      });
    }
```
I'll be honest, I am a bit new to git, so I'll try and familiarize myself with how to properly do a pull request and see what I can do. Once again, thanks!

**Comment by konsumer** [comment]
That's awesome! Thanks for figuring it out.

You can just edit file directly on github, if you're super-new to it, and don't want to check it out and stuff, and it will automatically fork to your own account, and there should be a "create PR button". If you like, I can add the code, but also I think it's cool to use PRs to track where everything came from, and add to your github stats!

I will comment, I'm not sure sure about the `var _this2 = this;` and `arguments` business. That seems like output from babel or something. Please use ES6, and [standard style](https://standardjs.com/) (so no semicolons) in [the source](https://github.com/konsumer/tplink-lightbulb/blob/master/src/lib.js).

One trick, instead of hoisting `this` around, is to use arrow-functions (like I do in a few places) as it doesn't modify `this`, but it's actually not needed here. `arguments` are also equally fragile (scope changes value) so I usually use ES6 "rest" operator:`(...args)`, but all that code is doing is setting a default, and default-values are built-in to ES6. I would probly do the same thing like this (inside the `TPLSmartDevice` class) :

```js
led (ledState = true) {
  return this.send({ system: { set_led_off: off: ledState ? 0 : 1 } })
}
```

This has a default of `true` which it seems like you intended, and skips the info-check which is unneeded (I do it in `power` because I need to check if it uses `set_relay_state` or `on_off`, but yours will be fine if there is no LED support.)

**Comment by konsumer** [comment]
Also, if you like, we could add it to the CLI, so people can set the LED state without writing code.

**Comment by migte** [comment]
Yup, you were right, that code works just as well and is much simpler. I'll take a look at how the CLI code works to see if I can understand it.

**Comment by konsumer** [comment]
I'm happy to help. I didn't have a packet-cap setup handy when you first asked, but you did that par (thanks!) so I can totally help with CLI part. Make a PR for the above code, and I will merge, and add a CLI entry for it.

**Comment by konsumer** [comment]
Ok, added `led` CLI to 1.5.3 and published.

```
tplight led <ip> <ledState>

Turn on/off LED indicator

Options:
  -h, --help  Show help                                                [boolean]
  --version   Show version number                                      [boolean]

Examples:
  cli.js led 10.0.0.200 off  Turn off the LED
  cli.js led 10.0.0.200 on   Turn on the LED
```

**Comment by konsumer** [comment]
Try it out and let me know if you got it working. I'm going to close this for now. thanks for your help!
