### ISSUE TITLE
Do LB200 bulbs work?

### ISSUE THREAD

**Issue by mark-hahn** [konsumer/tplink-lightbulb#22]
I just bought two LB200 bulbs.  I can't discover them.  Are they too new?

**Comment by konsumer** [comment]
No one has tested with them, but I could probably add LB200 & LB230, if you can share some network traffic (recorded with tcpdump) of discovering & talking to them. I followed the instructions [here](https://learn.adafruit.com/setting-up-a-raspberry-pi-as-a-wifi-access-point?view=all) and then connected to the fake wifi AP and recorded traffic, then later analyzed it with the [wireshark addon I modified](https://github.com/konsumer/tplink-lightbulb/blob/master/tplink-smarthome.lua).

**Comment by mark-hahn** [comment]
Thx.  I will do this.

Does controlling the bulb work when it is also set up for the kasa cloud
control or do I need to somehow reset it?  I don't need kasa in the long
run but I have set it up now to make sure the bulbs work, which they do.
Kasa will also provide the tcpdump net traffic.

**Comment by konsumer** [comment]
if you cycle power manually 3 times, it will reset the bulb. Then, with your phone on the fake wifi network, make sure tcpdump is running and setup the bulb in kasa app to use that network and do stuff like on/off/etc in kasa.

**Comment by mark-hahn** [comment]
will do

**Comment by konsumer** [comment]
I have a feeling it's a minor thing in the initial scan-broadcast, so hopefully it won't be too hard to work out.

**Comment by balvant813** [comment]
I have tested LB230 with tplight/tplink-lightbulb on Raspberry PI 3b.
It recognizes LB230 and I can use hsb etc and tplight sets it correctly. 
Sometime I get socket conn time outs.

**Comment by konsumer** [comment]
@balvant813 That's great. I assumed they used a similar protocol, but I'll add it to the support matrix.

**Comment by mark-hahn** [comment]
I removed a bulb from kasa, started tcpdump, reset the bulb to get the
three flashes, and kasa can't connect.  I've done this many times.  Before
trying tcpdump i've gotten it to connect twice so I'm sure the bulb is
good.  I'll try a different bulb.

Is there a way to reset the configuration in the bulb?  A fresh start might
help.

**Comment by konsumer** [comment]
The only way I have seen is to quickly turn the power off for the light (like at the switch) 3-5 times. It will flash when you reset it.

**Comment by mark-hahn** [comment]
I finally got a capture.  Unfortunately the file is big, 2200 packets,
because my wifi has a lot on it.   I paired the bulb, named it, turned the
light off then on, and finally faded to zero.

An nmap scan says there is a Tp-link Technologies node with an IP of
192.168.1.164.  I unscrewed the bulb and that IP went away. So I'm pretty
sure it is right.

 I looked for that IP in wireshark and found nothing.  But I'm not good at
wireshark filtering so it could be wrong.

**Comment by mark-hahn** [comment]
BTW, I'm using a TP-link wifi AP so don't be confused about that at
192.168.1.2.

**Comment by mark-hahn** [comment]
Mac is 50:C7:BF:F8:46:CA.

**Comment by mark-hahn** [comment]
eth.addr == 50:C7:BF:F8:46:CA  got some packets

**Comment by mark-hahn** [comment]
I got a scan to work.

```
$ tplight scan
Press Ctrl-C to stop
192.168.1.164 - My Smart Bulb - LB200(E26)
```
I might have tried scanning before Kasa configured them.

I'll try controlling it now.

**Comment by mark-hahn** [comment]
Everything seems to work now, so don't waste your time on the dump.  

Thanks and I'm sorry for your trouble.

**Comment by konsumer** [comment]
That's awesome! If ya'll want to test the full list of commands (the table on the front page) I'd be grateful, so I can ensure everything works for others.

**Comment by mark-hahn** [comment]
I've tested scan, info, power, and details and they all work.

One question; how do I dim?  I've tried `power` with brightness but I can't
get it to work.  The command always returns brightness:100.

**Comment by konsumer** [comment]
The `on` command can do it with the brightness flag. Do `tplight on --help`

**Comment by mark-hahn** [comment]
I'm using the node api.  If I do `light.power(false)` the light goes off.
If I do `light.power({brightness:100})` it comes on.  But numbers in
between just turn it on.

**Comment by mark-hahn** [comment]
BTW, `tplight on -b 10 192.168.1.163`  works.

**Comment by konsumer** [comment]
The params are `powerState, transition, options`, so the command is this:

```js
light.power(true, 0, {brightness: WHATEVER})
  .then(status => {
    // command completed. look at status to see how it went
  })
```

**Comment by mark-hahn** [comment]
Thanks.  It is working now.  I was sending a string instead of an integer.
This is one of the few times that a typed language would have helped.  :-)

So add the LB200 to your list.
