### ISSUE TITLE
Can this be use in ionic?

### ISSUE THREAD

**Issue by DerekLeeHH** [konsumer/tplink-lightbulb#26]
Hi, can this be use in ionic?

**Comment by konsumer** [comment]
You could use i on the server-side, then trigger it from your ionic app using HTTP+JSON or whatever you like. Basically just run a "lightbulb server" and then hit that in your app. An even easier/nicer dev-experience is to wrap it all in GraphQL, so you can use a fancy GraphQL client to play around with the queries.

I wrote a GraphQL interface [here](https://github.com/konsumer/tplink-graphql). It has a nice playground, built-in.

[Here](https://github.com/Quramy/ionic-apollo-simple-app) is a demo of how to use GraphQL with ionic.

**Comment by konsumer** [comment]
Marking this closed, as it's more of a question. but feel free to comment if you need anything.
