### ISSUE TITLE
support for other brands?

### ISSUE THREAD

**Issue by mark-hahn** [konsumer/tplink-lightbulb#28]
I have this running on two TP-Link bulbs and it works great. 

I just purchased a wifi bulb (CHICOYO a70rgbw)  that is sold under many names.  A color version costs only $15 on amazon.  At 1/3 the price I couldn't pass it up.

There are a lot of bulb controllers for node but I haven't found one with a matching bulb name.  I guess I could try each one but that would take forever.

Worst comes to worse I'll do some network sniffing on my own.  What a pain.

**Comment by konsumer** [comment]
Yeh, I am pretty sure that device uses a completely different protocol than this lib.

This lib is really just for tp-link devices, but on the plus-side they probly aren't using jenky fake XOR encryption, so it should be easier to work out with wireshark. It might just copy some other really popular lightbulb like the Phillips Hue or some-such. If it were me researching it, I'd try that angle, first, like see how it shows up in Alexa app, and see if other smart-bulb apps work with it. Use that as a clue to find a way to talk to it, for example [node-hue-api](https://github.com/peter-murray/node-hue-api).

Good luck!

**Comment by mark-hahn** [comment]
Thanks.

I sniffed like crazy but I couldn't see anything after the broadcasts even though my phone was controlling it.  I don't know what I was doing wrong.

I gave up and got another tp-link.  I found some LB200s on eBay for $20 rather than the $30 on Amazon.  It's a shame though.  The cheap bulb worked great, was RGB, and only cost $15.
