### ISSUE TITLE
Not working on windows

### ISSUE THREAD

**Issue by rolandg** [konsumer/tplink-lightbulb#29]
I just tried to run my scripts on windows. 
They hang during scan. The scripts run fine on linux.

Also `tplink scan` does never return.
I have enabled node in the firewall.

**Comment by shubhamkumarnayak** [comment]
I am also facing the same issue.

**Comment by konsumer** [comment]
I don't have a windows system to test with right now, but @gannonprudhomme 's solution makes sense. Try it out, and let me know if I can close the issue.

**Comment by rolandg** [comment]
No it doesn't change anything.

**Comment by AJaycup14** [comment]
I am also having issues getting scan to return anything. It used to work, now all of a sudden its not working anymore. I already reinstalled it and its still not working.

**Comment by konsumer** [comment]
Ok, I compiled some releases, so no one needs any particular node runtime or anything and it's all self-contained. Try out the [release](https://github.com/konsumer/tplink-lightbulb/releases/tag/v1.5.0) for your platform, and let me know if it still has issue.

**Comment by rolandg** [comment]
Fixed it for me.
Thanks
