### ISSUE TITLE
Tplight delay with commands

### ISSUE THREAD

**Issue by fartat** [konsumer/tplink-lightbulb#31]
Hi!
Don't know exactly if this is an issue, but no matter if I run commands from my laptop or from the Rasberry Pi but there is a 1-2 sec delay between the command and the actual thing happening. Does anybody else encounter this too? 
This however does not happen when I use the Kasa app from my phone.
Any help is appreciated. 
Thanks!

**Comment by konsumer** [comment]
I don't have this delay, but you might try [kasa_control](https://github.com/konsumer/kasa_control) if you are using it in code and want to hit the kasa servers.

The delay may come from something like warm-up time for node runtime or something else unrelated to the lib. Maybe try latest node version, to see if it improves startup time. I have thought that a C-based runtime would be cool (for use with microcontrollers, so they don't have to hit external servers, etc.) Maybe at some point I will refactor it in C, and make a lighter CLI that doesn't need a script runtime.

**Comment by konsumer** [comment]
Maybe in the meantime I could compile a runtime that might help with issue #29 (as it will included minimal node and all libs in one thing.)

**Comment by konsumer** [comment]
Ok, I compiled some releases, so no one needs any particular node runtime or anything and it's all self-contained. Try out the [release](https://github.com/konsumer/tplink-lightbulb/releases/tag/v1.5.0) for your platform, and let me know if it still has issue.

**Comment by konsumer** [comment]
Going this, due to inactivity, but let me know if you are still having issues.
