### ISSUE TITLE
Can you dim the light with this library?

### ISSUE THREAD

**Issue by mscheel** [konsumer/tplink-lightbulb#39]
I would like to set the light to 50% brightness (dim, not fully lit), is that possible?

I see brightness within the hsb command but I think that is a different brightness than what is in the Kasa app and changes how bright the bulb is lit.  At least that is what my tests have found.  

Thank you, this is a great library for turning on and off and changing color.

**Comment by konsumer** [comment]
Use the `-b` (or `--brightness`) flag for `on`:

```
tplink on -b 50
```

You can also set transition time if you want a  silky-slow dim:

```
tplink on -b 50 -t 5000
```

See `tplink on --help` for more info.

**Comment by konsumer** [comment]
Closing, but feel free to comment, if you have more questions related to this.
