### ISSUE TITLE
Support for LB130 color change

### ISSUE THREAD

**Issue by danodemano** [konsumer/tplink-lightbulb#4]
Hello,

What can be done to get support for this bulb?  On/off seems to work fine, just need color changing.  Let me know how I can help!

Thanks,
DAn

**Comment by konsumer** [comment]
I don't have a LB130, so I'd need to see a wireshark dump from your bulb to write code to interface with it.

Let me know if you need help with [these instructions](https://github.com/konsumer/tplink-lightbulb#wireshark) for setting up a raspberry pi and recording some traffic. It doesn't really need to be a pi, just any linux box with the bulb's network routed through it capturing packets (via tcpdump.)

**Comment by konsumer** [comment]
If you like, you can just setup an interceptor (linux box running tcpdump and wifi, with bulb routed using it) and I can do all the wireshark stuff. I just need the dump, really.

**Comment by danodemano** [comment]
Hey that was a fast response!  Tcpdump isn't an issue, done that a million times.  What I'm unsure about is how to route the bulbs traffic through a linux box.  I do have an unused Pi3 collecting dust at the moment along with an ESXi vm stack.  A nudge in the right direction would be great!

**Comment by danodemano** [comment]
Oh and I do have switches that can do port mirroring if that's easier, or actually just tcpdump from my firewall if you are looking for traffic from the bulb to the Internet.

**Comment by konsumer** [comment]
The way I did it was set the pi to pretend to be the WiFi access point, but if the bulbs traffic is routed through the Linux box (like it's your network's firewall) that should be fine.

**Comment by danodemano** [comment]
Just to confirm, traffic from the bulb to the Internet?   Thanks mate!

**Comment by konsumer** [comment]
Yep. Or start a WiFi access point on a Linux box and tell the bulb to connect to that wifi (which is what I did.)

**Comment by danodemano** [comment]
Thanks mate!  Will work on that today or tomorrow.  Trying to get this bulb 'integrated' into Home Assistant and the current Python library has...um issues.  Would love to use your library as it works great, stay tuned for a pcap.  Thanks again!

**Comment by konsumer** [comment]
Thank you!

**Comment by danodemano** [comment]
Nah, thank you!

[tplink.zip](https://github.com/konsumer/tplink-lightbulb/files/945851/tplink.zip)

See if this works.  I was changing the colors while running the tcpdump.  IP address of the bulb is 192.168.9.199  Thanks much!!

**Comment by DaveGut** [comment]
Not wanting to interrupt this thread, I am controlling the TP-Link LB-130 through Node.js (and SmartThings).  The most basic color command is:

{"smartlife.iot.smartbulb.lightingservice":{"transition_light_state":{"color_temp":0, "hue":${hue}, "saturation":${saturation}}}}
Note1:  'color_temp' must be 0 for color.  any other value will will be tuneable white.
Note2:  Hue is in range of 0 - 360.  Saturation is 0 - 100.
Note3:  for the LB130, color temp is from 2500 - 9000.  Setting below 2500 works, but the actual function appears to be 2500.
Note4:  The above command requires the bulb be on before sending.  To set color while turning on bulb, use 'ignore_default': 1.  This allows turn on while setting other parameters.

{"smartlife.iot.smartbulb.lightingservice":{"transition_light_state":{"ignore_default":1, "on_off": 1, "color_temp":0, "hue":${hue}, "saturation":${saturation}}}}

I just discovered the 'ignore_default' parameter and have tested it this AM.  It works for brightness, color_Temp, color (color_temp=0, hue, saturation), plus multiples (i.e., brightness + color_temp).

**Comment by konsumer** [comment]
@DaveGut thanks for the report. Would you guys mind testing this? I am happy to add a `setColor` function, if it's needed, but maybe I should just change `--color` in CLI to `--temperature`? I think the `--hue`, `--saturation`, and `--brightness` flags should allow you to set colors, but maybe a util function to convert from other color formats (RGB triplet or hex) would be helpful?

I think the L/V in HSL/HSV should map somehow to Luminence/Value, but I'm not sure of the range.

You can use function like these to convert other color formats:
https://gist.github.com/mjackson/5311256

or this more complete lib:
https://github.com/jfsiii/chromath

Can you guys try this out? Set `10.0.0.200` to the IP of your bulb.

```
tplight on 10.0.0.200 --hue=180 --saturation=100  # should be blue/teal
```

If you need to do it with code:

```js
const light = new Bulb('10.0.0.200') // your bulb IP
light.set(true, 100, {color_temp: 0, hue: 180, saturation: 100}) // should be blue/teal
  .then(status => {
    console.log(status)
  })
  .catch(err => console.error(err))
```

**Comment by danodemano** [comment]
@konsumer - just tried it out.  It turns the bulb on but doesn't seem to change the color.  It just comes on with the same color as when I last turned if off.

**Comment by konsumer** [comment]
@danodemano hmm. interesting. maybe this?
```
tplight on 10.0.0.200 --hue=180 --saturation=100 --color=0
```

**Comment by konsumer** [comment]
THe CLI also has raw JSON support, but I am hoping the H/S stuff actually works...

**Comment by danodemano** [comment]
Same result.  Output from the two commands:

```
root@ha:~# tplight on 192.168.9.199 --hue=180 --saturation=100
{ on_off: 1,
  mode: 'normal',
  hue: 312,
  saturation: 97,
  color_temp: 0,
  brightness: 75,
  err_code: 0 }
root@ha:~# tplight on 192.168.9.199 --hue=180 --saturation=100 --color=0
{ on_off: 1,
  mode: 'normal',
  hue: 0,
  saturation: 0,
  color_temp: 2500,
  brightness: 75,
  err_code: 0 }
root@ha:~#

```

**Comment by konsumer** [comment]
hmm. interesting.

**Comment by konsumer** [comment]
I wonder if it's the transition-time or `ignore_default`. Here are 3 to try:

```
tplight raw 192.168.9.199 '{"smartlife.iot.smartbulb.lightingservice":{"transition_light_state":{"ignore_default":1,"on_off":1,"color_temp":0,"hue":180,"saturation":100}}}'

tplight raw 192.168.9.199 '{"smartlife.iot.smartbulb.lightingservice":{"transition_light_state":{"transition_period": 1000, "ignore_default":1,"on_off":1,"color_temp":0,"hue":100,"saturation":100}}}'

tplight raw 192.168.9.199 '{"smartlife.iot.smartbulb.lightingservice":{"transition_light_state":{"on_off":1,"color_temp":0,"hue":80,"saturation":100}}}'
```


If so, I should remove those color flags, and just have a rgb/hsv command to set color.

**Comment by danodemano** [comment]
We're getting closer.  The first one gave me a teal color, the second was more green.  The third just turned it on to the same color as when I shut it off.  Output:

```
root@ha:~# tplight raw 192.168.9.199 '{"smartlife.iot.smartbulb.lightingservice":{"transition_light_state":{"ignore_default":1,"on_off":1,"color_temp":0,"hue":180,"saturation":100}}}'
{ 'smartlife.iot.smartbulb.lightingservice':
   { transition_light_state:
      { on_off: 1,
        mode: 'normal',
        hue: 180,
        saturation: 100,
        color_temp: 0,
        brightness: 75,
        err_code: 0 } } }
root@ha:~# tplight raw 192.168.9.199 '{"smartlife.iot.smartbulb.lightingservice":{"transition_light_state":{"transition_period": 1000, "ignore_default":1,"on_off":1,"color_temp":0,"hue":100,"saturation":100}}}'
{ 'smartlife.iot.smartbulb.lightingservice':
   { transition_light_state:
      { on_off: 1,
        mode: 'normal',
        hue: 100,
        saturation: 100,
        color_temp: 0,
        brightness: 75,
        err_code: 0 } } }
root@ha:~# tplight raw 192.168.9.199 '{"smartlife.iot.smartbulb.lightingservice":{"transition_light_state":{"on_off":1,"color_temp":0,"hue":80,"saturation":100}}}'
{ 'smartlife.iot.smartbulb.lightingservice':
   { transition_light_state:
      { on_off: 1,
        mode: 'normal',
        hue: 0,
        saturation: 0,
        color_temp: 2500,
        brightness: 75,
        err_code: 0 } } }
root@ha:~#

```

**Comment by danodemano** [comment]
If it would be easier for you to tinker we could setup a Skype or something can I can point my webcam at the light and give you access to the CLI, lol

**Comment by DaveGut** [comment]
The bulb state for the third run (below)  indicates that you had success.  Hue and saturation are zero.  Color temp is 2500.  So you did succeed in changing the parameters.  The color I get at 2500 color temp (and 75% brightness)  is a dark yellow, but noticeable to me.

**Comment by danodemano** [comment]
The third command just turns the light back on to whatever I had it set to before.  Turns out the first time was roughly the color you described.  Just tried it again with two other "whites" and it behaves the same way.  Only turn the bulb on to whatever it was set to before:

```
root@ha:~# tplight raw 192.168.9.199 '{"smartlife.iot.smartbulb.lightingservice":{"transition_light_state":{"on_off":1,"color_temp":0,"hue":80,"saturation":100}}}'
{ 'smartlife.iot.smartbulb.lightingservice':
   { transition_light_state:
      { on_off: 1,
        mode: 'normal',
        hue: 0,
        saturation: 0,
        color_temp: 9000,
        brightness: 75,
        err_code: 0 } } }
root@ha:~# tplight raw 192.168.9.199 '{"smartlife.iot.smartbulb.lightingservice":{"transition_light_state":{"on_off":1,"color_temp":0,"hue":80,"saturation":100}}}'
{ 'smartlife.iot.smartbulb.lightingservice':
   { transition_light_state:
      { on_off: 1,
        mode: 'normal',
        hue: 0,
        saturation: 0,
        color_temp: 4300,
        brightness: 75,
        err_code: 0 } } }
root@ha:~#
```

**Comment by konsumer** [comment]
I'm at work right now, but I'd be down for a video call later.

**Comment by danodemano** [comment]
Sounds good.  I should be around all afternoon/evening.  Pick a time and let me know.  I'm in EDT.  Do you have a preference on calling software?  I have Skype and Hangouts but can do just about anything.

**Comment by DaveGut** [comment]
That is correct.  You need to add (just prior to on_off), “ignore_default”:1.  This will solve the problem,

Example

'{"smartlife.iot.smartbulb.lightingservice":{"transition_light_state":{"ignore_default":1,"on_off":1,"color_temp":0,"hue":350,"saturation":100}}}'

**Comment by danodemano** [comment]
@DaveGut - that works, assuming it's supposed to be a deep kinda pink color.

**Comment by DaveGut** [comment]
Yes.  I was so glad to find the “ignore_default” option.  It reduced code complexity a great deal.

**Comment by konsumer** [comment]
Ok, so for each of the 3 commands I picked different colors to make sure you could see the change. The first 2 had `ignore_default`, and all of them had `color_temp=0`, so that is the missing part, as @DaveGut discovered.

I feel like we could resolve this a couple ways in the CLI:

1. always enable `ignore_default` for `on`, and `color_temp=0` by default. Does it otherwise work ok like this?
2. add a `--ignore-default` flag
2. Add a color command that sets `ignore_default` and `color_temp=0` and lets you use RGB/HSV vals to make it simple, and remove all the color-flags (`--hue`, `--saturation`, `--brightness`) which don't work on my color-temp only bulb, anyway.

In the lib, I could add `setColorRGB` and `setColorHSV`  wrapper functions that do something similar to option 3.

**Comment by danodemano** [comment]
I think option 3 is the best choice

**Comment by konsumer** [comment]
@danodemano I like that too. I will set it up.

**Comment by danodemano** [comment]
Sweet!  Let me know when you have something ready to test and I will thoroughly annoy my wife by changing the color constantly

**Comment by konsumer** [comment]
😀

**Comment by jhfoo** [comment]
Looking forward to your support for LB130!

**Comment by konsumer** [comment]
I think the support might already be there (with the  `--hue`, `--saturation`, `--brightness` flags.) I haven't had a chance to change the structure of the commands to make it easier to use RGB/HSV values yet, but it otherwise it should work fine.

**Comment by konsumer** [comment]
Ok, I reworked the CLI to work a little different. Seems neater, and now can do color-conversion from RGB hex.

```
Commands:
  scan                                      Scan for lightbulbs
  on <ip>                                   Turn on lightbulb
  off <ip>                                  Turn off lightbulb
  temp <ip> <color>                         Set the temperature of the lightbulb
                                            (for those that support it)
  hex <ip> <color>                          Set color of lightbulb using hex
                                            color (for those that support it)
  hsb <ip> <hue> <saturation> <brightness>  Set color of lightbulb using HSB
                                            color (for those that support it)
  cloud <ip>                                Get cloud info
  raw <ip> <json>                           Send a raw JSON command
  details <ip>                              Get details about the device

Options:
  -?, --help  Show help                                                [boolean]
```

I could really use testing from people who have a bulb that can change colors, as I have no way to test.

From this repo, if you run `npm i` and then `./node_modules/.bin/babel-node src/cli.js` will run it.

**Comment by DaveGut** [comment]
First time install of your app since Feb.  I was able to get the color to work as expected using hue and saturation parameters.  Was unsuccessful using the hex.
Command:  tplight on 192.168.0.103 --color 0 --hue 359 --saturation 100   WORKED
Command:  tplight on 192.168.0.103 --hex 391EE0    NO RESULT.  (command sent, no change in bulb, no error)
Command: tplight on 192.168.0.103 --hex #391EE0   NO RESULT.  (command sent, no change in bulb, no error)
Command: tplight hex 192.168.0.103 391EE0  UNKNOWN COMMAND

It may be my ignorance of the installation.

As far as ignore_default, in my code, I use this for all commands except off.  What it apparently does is reset the values included in the sent explicitly in the command, but other default_on_state commands are not changed.

**Comment by konsumer** [comment]
@DaveGut thanks for testing.

That looks like the old command (with working `--hue` and `--saturation` params for `on`. Glad that part is working, because I based the new stuff on that code.

I didn't publish to npm, because I thought I should test first, but since there aren't a lot of users, and it will make it easier to test, so I just published it now (as `1.1.2`.)

To install the new version, run `npm i -g tplink-lightbulb`

I structured everything in the new CLI in commands, to make it simpler and easier to separate them, so it should look like this:

```
tplight on 192.168.0.103
tplight hex 192.168.0.103 #391EE0
tplight hsb 192.168.0.103 359 100 100
```

**Comment by DaveGut** [comment]
Tested the two color variants.  For the hex variant the commands / results were:

$tplight hex 192.168.0.103 #391EE0
{
  "on_off": 1,
  "mode": "normal",
  "hue": 248,
  "saturation": 76,
  "color_temp": 0,
  "brightness": 49,
  "err_code": 0
}

$tplight hex 192.168.0.103 #2919E5
{
  "on_off": 1,
  "mode": "normal",
  "hue": 244,
  "saturation": 80,
  "color_temp": 0,
  "brightness": 49,
  "err_code": 0
}

$tplight hex 192.168.0.103  #9E607A
{
  "on_off": 1,
  "mode": "normal",
  "hue": 334,
  "saturation": 24,
  "color_temp": 0,
  "brightness": 49,
  "err_code": 0
}

Hue is typically 2 lower than the set-up value (I used my SmartThings integration to get the hex color value).  Insignificant and probably an error in my device handler (which calculates the hex from hue / saturation).

**Comment by konsumer** [comment]
Looks good @DaveGut. Thanks again for the testing. Does it seem like the colors are correct? If so, I will close this issue.

**Comment by DaveGut** [comment]
The color appear correct!  The code match that attained using the SmartThings color wheel.

**Comment by konsumer** [comment]
nice!

**Comment by danodemano** [comment]
@konsumer - I'm having issues with the new code.  Executing tplight hex 192.168.9.199 "#48258b"
 returns nothing and doesn't change the bulb color.  

If I run it without the quotes around the color it returns "Not enough non-option arguments: got 1, need at least 2"

Am I missing something stupid here?

**Comment by konsumer** [comment]
The quotes are needed because `#` is a comment in *nix shells. Are you sure the IP is right? Does `tplight scan` return that IP?

**Comment by danodemano** [comment]
The scan errors out:

```
Press Ctrl-C to stop
/usr/local/lib/node_modules/tplink-lightbulb/build/lib.js:303
        var msgBuf = Bulb.encrypt(Buffer.from('{"system":{"get_sysinfo":{}}}')
                                         ^
TypeError: undefined is not a function
    at Socket.<anonymous> (/usr/local/lib/node_modules/tplink-lightbulb/build/lib.js:303:42)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:104:17)
    at startListening (dgram.js:139:10)
    at dgram.js:230:7
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

```

That's the address I have in my database.  And it WAS working for on/off until I updated.  But even doing a "tplight off 192.168.9.199" now doesn't work.  That worked fine last night.

**Comment by konsumer** [comment]
What version of node are you using?  The old method of creating a buffer from a string has been deprecated.

**Comment by konsumer** [comment]
I could switch it back, but recent versions of node will complain.

**Comment by danodemano** [comment]
v0.12.5

For the record I know VERY little about node.  :)

**Comment by danodemano** [comment]
Debian 8.8 if that matters.  Trying to update says I'm always up to date:

```
root@ha:~# apt install nodejs
Reading package lists... Done
Building dependency tree
Reading state information... Done
nodejs is already the newest version.
nodejs set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by konsumer** [comment]
Ah, yeh, the version of nodejs that comes with debian/ubuntu is very old. That's like pre-1.0. The latest version is 8.1.2.

[Here](https://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version) is soem info about upgrading.

**Comment by danodemano** [comment]
Sweet, that got it.  Thanks!

**Comment by danodemano** [comment]
I lied.  The commands are actually returning something, but all they are doing is changing the brightness not the color:

```
root@ha:~# tplight hex 192.168.9.199 "#48258b"
{
  "on_off": 1,
  "mode": "normal",
  "hue": 260,
  "saturation": 57,
  "color_temp": 2500,
  "brightness": 34,
  "err_code": 0
}
root@ha:~# tplight hex 192.168.9.199 "#ff0000"
{
  "on_off": 1,
  "mode": "normal",
  "hue": 0,
  "saturation": 100,
  "color_temp": 2500,
  "brightness": 50,
  "err_code": 0
}
root@ha:~# tplight hex 192.168.9.199 "#000000"
{
  "on_off": 1,
  "mode": "normal",
  "hue": 0,
  "saturation": 0,
  "color_temp": 2500,
  "brightness": 0,
  "err_code": 0
}
root@ha:~# tplight hex 192.168.9.199 "#ffffff"
{
  "on_off": 1,
  "mode": "normal",
  "hue": 0,
  "saturation": 0,
  "color_temp": 2500,
  "brightness": 100,
  "err_code": 0
}
root@ha:~#

```

**Comment by konsumer** [comment]
Let's make a new issue so everyone else on the thread doesn't get mega-spammed. :)

**Comment by DaveGut** [comment]
You have the color temp set.  It MUST be zero for color to work.  The cmd to bolb for hue/saturation should include color temp == 0.



Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by konsumer** [comment]
I will add this.

**Comment by DaveGut** [comment]
Sorry for not testing color temp earlier.  Also, I have been limited since i was driving from Dallas to Scranton over the past few days.

**Comment by konsumer** [comment]
Oh no, great work. In the current version it zeroes out temp, seems to be working for @danodemano
