### ISSUE TITLE
Adding wifi setup functionality

### ISSUE THREAD

**Issue by sergimn** [konsumer/tplink-lightbulb#55]
Another good feature would be to add the capability of connecting the devices to a WiFi network, thus removing the necessity of the Kasa app for setting up the device

**Comment by konsumer** [comment]
Can you do some traffic analysis of the setup process?

**Comment by sergimn** [comment]
Unfortunately, this feature came to my mind as I have no means to do the setup without a smartphone. When I get access to one I can upload a ```.pcap``` file or even take a look at it (I guess the process won't be complicated?) but it may take some weeks :(

**Comment by konsumer** [comment]
I am pretty busy with other stuff right now, so I probably won't have time to get to this, anytime soon.

It's a bit tricky to record because it has it's own wifi you connect to, to set it up, so you'd need to capture the traffic on a phone (or a computer attached to the setup network, before the setup routine is run.) It may be very tied to kasa-servers (like it's totally possible the devices do not allow anything too advanced without talking to kasa servers.)

This lib doesn't use kasa once the light is setup, though, it interacts with the devices directly, over wifi. I made [another lib](https://github.com/konsumer/kasa_control) that does use kasa, if you want that (allows remote interaction, if you are not on the local network.) So, an alternative approach might be to connect your computer to the device's setup-wifi and control it from there. it would mean using a new wifi (not authenticated!) for each light, which sounds like a terrible idea, but might be fun for experimenting.

**Comment by sergimn** [comment]
No problem, I'll try to look into it myself even though I've never done anything in JS. I know some networking, so that part won't be a problem. 

I've seen your other library and it's quite interesting but it doesn't fit my necessities right now because I have a bulb that isn't connected anywhere

> which sounds like a terrible idea

Yep, it does hahaha. I don't mind having it open while I test (at the end of the day there is no workaround) but definitely I'm not going to use this solution. I guess I'll have to look into it myself

**Comment by konsumer** [comment]
What is the other library? If they have this functionality, I can take a look at it.

**Comment by sergimn** [comment]
There is no other library, I meant your library, the one you linked in your comment :slightly_smiling_face:

**Comment by sergimn** [comment]
Ok so thanks to the wonderful developers of Wireshark TP-Link filters I got it. It doesn't seem too difficult to implement as long as TP-Link hasn't set up artificial barriers for making it difficult.
I'll try to do it next week. The current plan is to add three functionalities:

- Scan Wifi networks
- Connect to a network
- Disconnect from a network (touchy because then you are not going to have connectivity again)

Do you have any specific names you would like to call the functions to call this? Or any advice in general?

**Comment by konsumer** [comment]
That is great news!

Sounds like it may be very tricky for cross-platform wifi-control.

I found these: 

- [node-wifi](https://www.npmjs.com/package/node-wifi) - seems like it would work, but no mac disconnect support.
- [wifi-control](https://www.npmjs.com/package/wifi-control) - seems similar, but no "disconnect at all"

> Do you have any specific names you would like to call the functions to call this? Or any advice in general?

I am thinking this may be nice as a separate script, that we keep in same repo, to help people out, so main lib doesn't gain a wifi-lib dep, but also it would be a cool feature for the CLI, so I'm totally fine with whichever wifi-lib you get working. I bet using `send()` from this lib would help with the actual comm.

After that I would maybe suggest this flow, based on what wifi-libs can do:

- Scan Wifi networks
- Record current network (either by user-input, or if the libs let you do it directly that'd be cool)
- Connect to new device's network
- `scan()` the network to find the device, unless you already know the IP
- Do the magic (not sure what that is, but basically use `send()` to tell the one device on the network it's new wifi settings)
- Connect to a user's old network

A simple snippet to send a direct command to a all devices on a current wifi network would be similar this:

```js
import TPLSmartDevice from 'tplink-lightbulb'

// setup every light on current wifi
TPLSmartDevice.scan()
  .on('light', light => {
    // I dunno what this is, use what you learned
    const setup_stuff = {

    }
    // this does the encryption/json for you
    light.send(setup_stuff)
  })

// if it only has one IP:
const list = new TPLSmartDevice('10.0.0.1') // or whatever the IP is

const setup_stuff = {
}

light.send(setup_stuff)

```

use `node -r esm yourscript.js` to run this without a need for babel (to handle `import` and stuff)

If you work it out (or share what you discovered here) I can just add it to the CLI, even though I'm busy. it's a cool feature, and it should go pretty quick if you've done all the research.

**Comment by konsumer** [comment]
Also, I forgot to mention, but I can do traffic analysis of setup process. I totally forgot you are without phone to do it, and it's super-useful to verify how the legit traffic looks.

**Comment by konsumer** [comment]
We might even be able to use [androiddump](https://www.wireshark.org/docs/man-pages/androiddump.html) to capture from a real android device.

**Comment by sergimn** [comment]
Hey :slightly_smiling_face: 

My plan wasn't so ambitious, I was thinking on relying on the user manually connecting to the open WiFi network TP-Link devices create on setup to interact with it, keeping the library simple. The good think about this is that TP-Link devices have a DHCP server and the devices themselves always have the IP 192.168.0.1, thus making the setup process quite easy. We could also call `scan` under the hood to make sure we have the correct IP or allow the user to manually set a destination IP (as all other commands allow)

The problem (if you could even call that a _problem_) with what you proposed with mangling WiFi settings is that the user would need to give root permissions for some steps as getting the password of the saved networks is not something you can do in userspace.

The plan is to do something as you pointed out in your code snippet and put correct command for the bulb to list their accessible AP's and connect to one of those.

The JSON to send for connecting to one AP should look like something like this, but please, let me do the pull request, it will be my first code contribution to a project ^^
```
{
    "smartlife.iot.common.softaponboarding": {
        "set_stainfo": {
            "cipher_type": 2,
            "key_type": 3,
            "password": "12345678",
            "ssid": "MyWiFi"
        }
    },
    "context": {
        "source": "xxx-xxxx-xxxx-xxxx-xxxx-xxxx"
    }
}
```

I already got a smartphone to the traffic analysis (well, with the help of [Wireshark and monitor mode](https://wiki.wireshark.org/CaptureSetup/WLAN)). That's how I got the data so I will not do this blindly but when I have an implementation it would be nice to test with more devices and make sure it doesn't break anything.

**Comment by sergimn** [comment]
I just did a test with `tplight raw` and the device connected to my WiFi, so it seems like it won't be a problem to implement :smiley:

**Comment by konsumer** [comment]
> The problem (if you could even call that a problem) with what you proposed with mangling WiFi settings is that the user would need to give root permissions for some steps as getting the password of the saved networks is not something you can do in with normal user permissions.

Ah yes, this is a good consideration. Again, maybe as a separate script this would be helpful to people. They could always run `sudo node SCRIPT` and we could just keep it totally separate from the main CLI.

> I just did a test with tplight raw and the device connected to my WiFi, so it seems like it won't be a problem to implement

That is very good news! It might be possible to just write the whole thing as a bash/batch script, if you wanted to. Like you could just tell the user to do stuff that requires extra perms like echo "ok, switch to tplight-WHATEVER, now, and hit enter here to continue" that kind of thing. After that you can use `tplight raw` to do stuff. I dunno, go with whichever feels more comfortable (js or shell script or whatever.)

> The JSON to send for connecting to one AP should look like something like this, but please, let me do the pull request, it will be my first code contribution to a project

Of course! This is all you. You got it.

**Comment by konsumer** [comment]
I think I'm going to close this issue for now, as we have commands & api-functions to do basic wifi setup. If you want to write a script, or add some wiki directions about it, that'd be great, but not totally required. Thanks for the great PR!
