### ISSUE TITLE
NPM package cannot install

### ISSUE THREAD

**Issue by AndrewJLang** [konsumer/tplink-lightbulb#58]
Title says issue, npm install of the package does not work. It is relying on cli.js file but is not able to be found in the installation process. Here is error message after running `npm install tplink-lightbulb`:

![image](https://user-images.githubusercontent.com/43326382/117906441-c2005f00-b289-11eb-9242-77677c2c4930.png)

Any help would be appreciated, I am able to successfully install older package version such as 1.5.4 but not the current one.

**Comment by konsumer** [comment]
Should be fixed in 1.6.4. Going to close, but lemme know if it's not working.
