### ISSUE TITLE
Color temperature issue

### ISSUE THREAD

**Issue by Kinny092** [konsumer/tplink-lightbulb#59]
Hi, 

Not entirely sure if this is an issue but it is strange if it isnt.
I tried to change color temp for four LB models and they did not change to orange-ish or blue-ish.
The command I issued is indeed tplight temp <ip> 1 as well as 10000 as stated in the example.

LB 100
```
{
  "on_off": 1,
  "mode": "normal",
  "hue": 0,
  "saturation": 0,
  "color_temp": 2700,
  "brightness": 100,
  "err_code": 0
}
```
LB 110, LB 120, LB 130
```
{
  "err_code": -10000,
  "err_msg": "Invalid input argument"
}
```
To my understanding, these LB are EOL and their specs for color temp are as follow

LB 100, LB 110 - 2700K 7SDCM
LB 120 - 2700K - 6500K
LB 130 - 2500K - 9000K & RGB Full color

**Comment by konsumer** [comment]
Which example are you using? It's entirely possible the example has an out-of-range number, as I tested with the lights I had on-hand at the time. Is it not working at all, or is it just an out-of-range value?

**Comment by konsumer** [comment]
Ah, you probably mean the [CLI examples](https://github.com/konsumer/tplink-lightbulb/blob/master/src/cli.js#L145-L146). Is there a better example value you would suggest? It's just meant to show how the command works, so it's ok if it doesn't work for every device, but maybe we should put values in there that work for more devices.

**Comment by Kinny092** [comment]
@konsumer it now works, I think I know why. last night i was focussing on my LB 130 which is in my room but that dosent matter. the value 1 and 1000 does not work for any of those model as LB 100 and 110 are fixed at 2700K, LB 120 and LB 130 will not take 1 or 1000 because it cant go more daylight than its designed for. when i did a 3000, 4000, 5000 on the LB 130, it instantly change the temp color because it is in the range of 2500 and 9000. i managed to change it back to my default 5285 so its surely working. sorry about that, there is no issue with your code its just user error, its educational. you may close this issue ;)

![image](https://user-images.githubusercontent.com/25901267/119073499-fc31d500-b9dc-11eb-9eef-2254869055ba.png)
```
┌─[✗]─[kin@kin-hpelitex21012g1]─[~]
└──╼ $tplight temp 192.168.1.110 5000
{
  "on_off": 1,
  "mode": "normal",
  "hue": 0,
  "saturation": 0,
  "color_temp": 5000,
  "brightness": 100,
  "err_code": 0
}
┌─[kin@kin-hpelitex21012g1]─[~]
└──╼ $tplight temp 192.168.1.110 4000
{
  "on_off": 1,
  "mode": "normal",
  "hue": 0,
  "saturation": 0,
  "color_temp": 4000,
  "brightness": 100,
  "err_code": 0
}
┌─[kin@kin-hpelitex21012g1]─[~]
└──╼ $tplight temp 192.168.1.110 3000
{
  "on_off": 1,
  "mode": "normal",
  "hue": 0,
  "saturation": 0,
  "color_temp": 3000,
  "brightness": 100,
  "err_code": 0
}
┌─[kin@kin-hpelitex21012g1]─[~]
└──╼ $tplight temp 192.168.1.110 5285
{
  "on_off": 1,
  "mode": "normal",
  "hue": 0,
  "saturation": 0,
  "color_temp": 5285,
  "brightness": 100,
  "err_code": 0
}
```

**Comment by konsumer** [comment]
Glad it's working ok. I'd be happy to update the examples to `2500` and `9000`, if that makes more sense, though. I probably just put those values in without paying any attention.

**Comment by konsumer** [comment]
Changed example values in tplink-lightbulb@1.6.5
