### ISSUE TITLE
[ERR_REQUIRE_ESM] - when referencing the pkg as CommonJS

### ISSUE THREAD

**Issue by PieterT2000** [konsumer/tplink-lightbulb#66]
When referencing your amazing package using,
```javascript
const TPLSmartDevice = require('tplink-lightbulb')
```
I get this error 
![image](https://user-images.githubusercontent.com/47913749/177004146-4b819f81-2dd3-48b3-b581-9f0def3e1f5c.png)

I suspect the reason is that `exports` in package.json takes precedence over `main` according to the Node.js docs. I will shortly after create a pr with a workaround.

**Comment by konsumer** [comment]
I use microbundle to package for all, and thatused to be the recommendation for setting it up, but they say to do this now:

```
```

**Comment by konsumer** [comment]
Once CI is finished `1.7.9` should have it working. Please test and let me know if that resolve the issue.

**Comment by PieterT2000** [comment]
A huge thank you David for responding so quickly! Keep up your great work!
