### ISSUE TITLE
Network scan for devices interferes with ability to change name of device

### ISSUE THREAD

**Issue by phrenopolis** [konsumer/tplink-lightbulb#71]
Code to scan the network for devices helpfully sets TPLSmartDevice.name to the name of the device before returning the object, however, in so doing it overwrites the function for changing the device name, also called TPLSmartDevice.name. If you try to scan the network for all of its devices, and then you ever try to reference those objects to change device names, you get a TypeError.
Workaround: If you use the IP address from your scan data to create a NEW TPLSmartDevice object, you can use that one to set the name. It just seems messy that you have to.

**Comment by konsumer** [comment]
Hmm, I am not sure I fully understand the issue. The constructor uses an IP, and all other requests should be using that IP. Can you share a code example of the problem?

**Comment by konsumer** [comment]
I do think the overwriting of `name` is a bug as a sidenote. Maybe the async getter should be `getName`?

**Comment by phrenopolis** [comment]
> I do think the overwriting of `name` is a bug, as a sidenote. Maybe the async getter should be `getName`?

It's a setter, so, probably setName?

**Comment by konsumer** [comment]
Ah, yes, well that seems fine.

**Comment by phrenopolis** [comment]
My own actual code example would be longish to sort through, but the gist is:
1. Declare an array called deviceList[]
2. Call TPLSmartDevice.scan(), which returns a bunch of instances of TPLSmartDevice. Push all of the results into deviceList[].
3. Try to call deviceList[i].name("My New Device Name")
This last step will generate an error (because the scan() in step two puts a text string in .name and overwrites the function you try to call in step 3)

**Comment by konsumer** [comment]
Yep, no prob, I see the issue. When you do call `getName` (as it will be renamed` make sure to `await` or `then` it, as it returns a promise. I will try to make an update, tonight.

**Comment by konsumer** [comment]
`1.8.0` should have `getName`. I will close, but feel free to comment more, if that doesn't work for ya.
