### ISSUE TITLE
TypeError: undefined is not a function - check for existence of Buffer.from

### ISSUE THREAD

**Issue by CantonsCobb** [konsumer/tplink-lightbulb#9]
After installing the tplink-lightbulb package, I have come across an error stating "TypeError: undefined is not a function." From the attached image, it is shown that tplight has been installed via the command prompt that displays the help menu for the scan command. However when attempting to run the scan, the "TypeError" message appears. The scan is not performed. In addition, I have successfully pinged the IP of the bulb, and tried the on/off commands. The commands to not trigger a response in the bulb, nor do they throw an error.

It is very possible I made an error on install. Please let me know if there is more information I need to provide.

![typeerror](https://user-images.githubusercontent.com/14893267/28254135-948cbea8-6a6f-11e7-9198-67f06c0c767a.png)

**Comment by konsumer** [comment]
There was a change with how to make a new buffer from a string, with node. The old method is deprecated, so I use the new syntax.  Please upgrade your node install.

**Comment by CantonsCobb** [comment]
That was it, thank you very much. A minimum version number in the readme may be helpful for future users.

**Comment by konsumer** [comment]
That is a great idea. I was also thinking about testing for `Buffer.from`. When I get a minute, I'll change the code. For now, I changed the title of the issue. Thanks for the report.

**Comment by konsumer** [comment]
Resolved in #f777b8ec940
